apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: myweb-app
    type: front-end
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx-container
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
